--------- model parameters ---------
model: pix2pixHD
input_nc: 3
label_nc: 0
output_nc: 3
netG: local
ngf: 64
num_D: 3
ndf: 64
norm: instance
init_type: normal
init_gain: 0.02
use_dropout: True

-------- instance-wise features --------
use_instance_map: False
use_instance_feat: False
use_label_feat: False

--------- training parameters ---------
lr: 0.0002
beta1: 0.5
lr_fix_epochs: 50
lr_decay_epochs: 50
lr_policy: linear

--------- dataset parameters ---------
batch_size: 96
direction: AtoB
pool_size: 0

--------- additional parameters ---------
train_folder: datasets/kaggle_landscape/train
eval_folder: datasets/kaggle_landscape/val
