--------- model parameters ---------
model: pix2pix
input_nc: 3
output_nc: 3
netG: unet_256
ngf: 64
netD: basic
ndf: 64
gan_mode: vanilla
norm: batch
init_type: kaiming
init_gain: 0.02
use_dropout: True

--------- training parameters ---------
lr: 0.0002
beta1: 0.5
lr_fix_epochs: 100
lr_decay_epochs: 100
lr_policy: linear

--------- dataset parameters ---------
batch_size: 128
direction: AtoB
pool_size: 0

--------- additional parameters ---------
train_folder: datasets/kaggle_landscape/train
eval_folder: datasets/kaggle_landscape/val
