--------- model parameters ---------
model: cyclegan
input_nc: 3
output_nc: 3
ngf: 64
ndf: 64
netG: unet_256
netD: basic
norm: batch
init_type: kaiming
init_gain: 0.02
use_dropout: True

--------- model parameters ---------
batch_size: 128
n_epochs: 100
n_epochs_decay: 100
lr: 0.0002
beta1: 0.5
gan_mode: lsgan
lr_policy: plateau
lr_decay_iters: 50

--------- additional parameters ---------
train_folder: 'datasets/edges2shoes/train'
eval_folder: 'datasets/edges2shoes/val'
